{
 "title": "内容分发网络(CDN)",
 "description": "【华为云CDN监控指标说明】https://support.huaweicloud.com/usermanual-cdn/cdn_01_0254.html",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DomainName",
    "label": "分发域名",
    "query": {
     "query": "label_values(huaweicloud_sys_cdn_req_num, domain_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "总请求数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_req_num{domain_name=~'$DomainName'}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "回源带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_bw{domain_name=~'$DomainName'}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "状态码汇总2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_http_code_2xx{domain_name=~'$DomainName'}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "平均请求耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_avg_req_time{domain_name=~'$DomainName'}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "CDN命中流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_hit_flux{domain_name=~'$DomainName'}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "CDN流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_flux{domain_name=~'$DomainName'}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "回源流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_flux{domain_name=~'$DomainName'}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "回源失败次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "huaweicloud_sys_cdn_bs_fail_num{domain_name=~'$DomainName'}",
     "legendFormat": "{{domain_name}}"
    }
   ]
  }
 ]
}