{
 "title": "DDOS高防",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "huaweicloud_epinfo" } }
  ]
 },
 "panels": [
  {
   "title": "$EPS:业务带宽利用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddos_instance_service_bandwidth_usage{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:入带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddos_instance_internet_in_rate{epId=~\"$EPS\"}",
     "legendFormat": "{{name}} unit: {{unit}}"
    }
   ]
  },
  {
   "title": "$EPS:并发连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddos_instance_concurrent_connection{epId=~\"$EPS\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$EPS:攻击带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddos_instance_drop_rate{epId=~\"$EPS\"}",
     "legendFormat": "{{name}} unit: {{unit}}"
    }
   ]
  },
  {
   "title": "$EPS:回源带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddos_instance_back_to_source_rate{epId=~\"$EPS\"}",
     "legendFormat": "{{name}} unit: {{unit}}"
    }
   ]
  },
  {
   "title": "$EPS:新建连接",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "huaweicloud_sys_ddos_instance_new_connection{epId=~\"$EPS\"}",
     "legendFormat": "{{name}} unit: {{unit}}"
    }
   ]
  }
 ]
}