{
 "title": "分布式消息服务RocketMQ",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "reliablemq_instance_id",
    "label": "RocketMQ实例",
    "query": {
     "query": "query_result(huaweicloud_sys_dms_instance_produce_msg{})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "实例-消息生产数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_instance_produce_msg{reliablemq_instance_id=~\"$reliablemq_instance_id\"}",
     "legendFormat": "{{instanceName}},{{reliablemq_instance_id}}"
    }
   ]
  },
  {
   "title": "实例-消息消费数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_instance_consume_msg{reliablemq_instance_id=~\"$reliablemq_instance_id\"}",
     "legendFormat": "{{instanceName}},{{reliablemq_instance_id}}"
    }
   ]
  },
  {
   "title": "实例-主题数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_current_topics{reliablemq_instance_id=~\"$reliablemq_instance_id\"}",
     "legendFormat": "{{instanceName}},{{reliablemq_instance_id}}{{kafka_instance_id}}"
    }
   ]
  },
  {
   "title": "实例-队列数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_current_queues{reliablemq_instance_id=~\"$reliablemq_instance_id\"}",
     "legendFormat": "{{instanceName}},{{reliablemq_instance_id}}"
    }
   ]
  },
  {
   "title": "实例-堆积消息数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_instance_accumulation{reliablemq_instance_id=~\"$reliablemq_instance_id\"}",
     "legendFormat": "{{instanceName}},{{reliablemq_instance_id}}"
    }
   ]
  },
  {
   "title": "实例磁盘容量使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_instance_disk_usage{reliablemq_instance_id=~\"$reliablemq_instance_id\"}",
     "legendFormat": "{{instanceName}},{{reliablemq_instance_id}}"
    }
   ]
  },
  {
   "title": "节点-消息生产数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_produce_msg{reliablemq_instance_id=~\"$reliablemq_instance_id\"}",
     "legendFormat": "{{instanceName}},{{reliablemq_instance_id}},{{reliablemq_broker}}"
    }
   ]
  },
  {
   "title": "节点-消息生产数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_broker_produce_msg{reliablemq_instance_id=~\"$reliablemq_instance_id\"}",
     "legendFormat": "{{instanceName}},{{reliablemq_instance_id}},{{reliablemq_broker}}"
    }
   ]
  },
  {
   "title": "主题-消息生产数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_topic_produce_msg{reliablemq_instance_id=~\"$reliablemq_instance_id\"}",
     "legendFormat": "{{instanceName}},{{reliablemq_instance_id}},{{reliablemq_topics}}"
    }
   ]
  },
  {
   "title": "主题-消息生产数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_topic_produce_msg{reliablemq_instance_id=~\"$reliablemq_instance_id\"}",
     "legendFormat": "{{instanceName}},{{reliablemq_instance_id}},{{reliablemq_topics}}"
    }
   ]
  },
  {
   "title": "消费组-消息消费数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_group_consume_msg{reliablemq_instance_id=~\"$reliablemq_instance_id\"}",
     "legendFormat": "{{instanceName}},{{reliablemq_instance_id}},{{reliablemq_groups}}"
    }
   ]
  },
  {
   "title": "死信队列-死信主题消息量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "expr": "huaweicloud_sys_dms_dlq_accumulation{reliablemq_instance_id=~\"$reliablemq_instance_id\"}",
     "legendFormat": "{{instanceName}},{{reliablemq_instance_id}},{{reliablemq_dlq_topics}}"
    }
   ]
  }
 ]
}